export const getCurrency = state => state.getIn(["exchange", "currency"])
export const getCoin = state => state.getIn(["exchange", "coin"])
export const getPairs = state => state.getIn(["exchange", "pairs"])
export const getValue = state => state.getIn(["exchange", "value"])
export const getResult = state => state.getIn(["exchange", "result"])